#!/bin/bash +x

port=$1

#CONTAINER_IP=$(sudo lxc info price | grep eth0 | grep -w inet | cut -f3)

i=0
while true; do
    health=$(curl -sm2  http://$port/actuator/health)
    if [ "$health" = '{"status":"UP"}' ]
    then
	break;
    fi
    sleep 1
    i=$((i+1))
    if [ $i -eq 60 ]
    then
	echo "server not up"
	exit 1
    fi
done

cd scripts
curl -X PUT -H "Content-Type: application/json" http://$port/prices/alex/FR123456/1995 --data "@prices.json"
status=$(curl -sI http://$port/prices/alex/FR123456/1995 | head -n 1)
echo $status | grep 200
if [ $? -eq 0 ]
then
    exit 0
else
    exit 1
fi
